/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_EnrollmentrxRx_Enrollment_Opa0LTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_EnrollmentrxRx_Enrollmenta0LTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new EnrollmentrxRx__Enrollment_Opportunity__c());
    }
}